# Generated by Django 3.2.6 on 2021-09-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210913_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='high_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='low_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='medium_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
