# Generated by Django 3.2.6 on 2021-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210913_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_counter', models.PositiveIntegerField(default=0)),
                ('medium_counter', models.PositiveIntegerField(default=0)),
                ('low_counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='high_counter',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='low_counter',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='medium_counter',
        ),
    ]
