# Generated by Django 3.2.6 on 2021-09-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210914_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityCount',
        ),
    ]
